### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [buserror/touchstream#3]
I would like to point out that identifiers like “[`__FIFO_DECLARE__`](https://github.com/buserror/touchstream/blob/9c9c2f6faeaf486d62c07671295cd4e735e86f57/src/fifo_declare.h#L27 "Update candidate")” and “[`__SH_DISPLAY_H___`](https://github.com/buserror/touchstream/blob/9c9c2f6faeaf486d62c07671295cd4e735e86f57/src/ts_display.h#L46 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by buserror** [comment]
No, that's just pedantry. The day these clash with something from the C library, I'll eat my hat :-)

Thanks tho. Is that some sort of bot  you are using? because I run my code thru cppcheck, and smatch, and scan-build (clang static analyser) and as stupid as the warning comes sometimes, they don't come anywhere near as these :-)

**Comment by elfring** [comment]
Additional analysis tools can point software development concerns out for further considerations.

How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
